### ISSUE TITLE
"null://undefined" added to esriConfig.defaults.io.corsEnabledServers after sign in

### ISSUE THREAD

**Issue by stdavis** [agrc/agrc.ijit#68]
This causes issues with layer-selector.

Need to look at a way to prevent or just manually remove it after successfully signing in via something like this:
```js
esriConfig.defaults.io.corsEnabledServers.splice(
    esriConfig.defaults.io.coresEnabledServers.indexOf('null://undefined'), 1);
```

**Comment by steveoh** [comment]
I don't think this belongs here because corsEnabledServers is not modified in this project. The problem stems from somewhere else. I'm still looking for where that is.
